site_name: Madek User Dokumentation
docs_dir: source
site_dir: build
theme_dir: theme_dir
extra_css: [styles.css]
pages:
- Home: 'index.md'
- Software Madek:
    - Was ist Madek?: 'software/01-madek.md'
    - Grundkonzepte der Software: 'software/02-concepts.md'
    - Benutzeroberfläche: 'software/03-interfaces.md'
    - Arbeiten mit Medieneinträgen: 'software/04-mediaentries.md'
    - Ordnen & Vernetzen: 'software/05-organize.md'
    - Erkunden & Suchen: 'software/06-search.md'
    - FAQ: 'software/07-faq.md'
    - Glossar: 'software/08-glossary.md'
    - Madek-Player: 'software/09-player.md'
    - Madek-API: 'software/10-api.md'
    - Roadmap: 'software/11-roadmap.md'
- Medienarchiv der Künste (ZHdK): 
    - Vertiefungsarchive: 'instance/zhdk/01-specializationarchives.md'
    - Leitfaden für die Eingabe von Abschlussarbeiten: 'instance/zhdk/02-complementaryworks.md'
    - Projektschaufenster auf der Website der ZHdK: 'instance/zhdk/03-projectswebsite.md'
    - Ablieferung ans Archiv: 'instance/zhdk/04-archive.md'
    - Bilder offline vorbereiten: 'instance/zhdk/05-prepare.md'
    - Fachvokabulare: 'instance/zhdk/06-vocabulary.md'
    - Logins für Externe: 'instance/zhdk/07-externallogins.md'
    - Hyperaura: 'instance/zhdk/08-hyperaura.md'
    - Persönliches Portfolio: 'instance/zhdk/09-personalportfolio.md'
    - Darstellende Künste / Performancekunst: 'instance/zhdk/10-performingarts.md'
    - Musikaufführungen: 'instance/zhdk/11-musicperformances.md'
    - Nutzungsbedingungen: 'instance/zhdk/12-usageterms.md'
markdown_extensions:
    - smarty
    - toc:
        permalink: True